### ISSUE TITLE
Missing dist file in 2.0.0

### ISSUE THREAD

**Issue by Toilal** [ibufu/vue2-scrollspy#10]
`2.0.0` package does not contain `./dist/index.js` file. Could you fix this with a new release @ibufu ?

**Comment by Toilal** [comment]
`/dist/*` should be removed from `.npmignore`

**Comment by Toilal** [comment]
You just have to build and release with current master, https://github.com/ibufu/vue2-scrollspy/commit/e9b5030128a8ed1eb46c4ebb0d1b0819a20fc8b2 should fix this. If you agree to give rights to me on npm registry, I could perform releases with this account : https://www.npmjs.com/~toilal

**Comment by ibufu** [comment]
Sorry

**Comment by ibufu** [comment]
I add you to collaborators of npm.
