### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by pepzwee** [ibufu/vue2-scrollspy#2]
I was testing this on Chrome, everything was working fine. Then I switched to Firefox and Firefox Dev and saw that it was not updating the active positions nor scrolling to the elements when clicked on.

Neither does the example page https://ibufu.github.io/vue2-scrollspy/ update the menu on the left on Firefox.

**Comment by ibufu** [comment]
@pepzwee , I found that ```document.body.scrollTop```  is always 0 on Firefox. I am looking for a  solution.

**Comment by ibufu** [comment]
Fixed in 1.1.2
