### ISSUE TITLE
Add cdn for use in browser

### ISSUE THREAD

**Issue by rklak** [ibufu/vue2-scrollspy#26]
I have a simple Vue js app written in javascript without node js support. It would be great to use this library in browser by some CDN.

**Comment by ibufu** [comment]
done

**Comment by rklak** [comment]
[Vue warn]: Failed to resolve directive: scroll-spy-active

How to add it to Vue? what is the object name?

**Comment by ibufu** [comment]
https://jsfiddle.net/ibufu/nw0zczLx/
It automatically calls `Vue.use()` if Vue is available as a global variable.
