### ISSUE TITLE
IOS9 support

### ISSUE THREAD

**Issue by Anima-t3d** [ibufu/vue2-scrollspy#30]
<img width="752" alt="screen shot 2018-07-18 at 19 33 41" src="https://user-images.githubusercontent.com/830386/42879852-b0ce3dbe-8ac4-11e8-92c0-d104fadb955c.png">
There are 2 issues which breaks JS interaction in vue app when using scroll-spy on mobile device with IOS9

I managed to trace these issues down to IOS 9 and this package. IOS10+ is not affected.

Related to: https://github.com/webpack/webpack/issues/3928

**Comment by ibufu** [comment]
try v2.3.1

**Comment by Anima-t3d** [comment]
![image](https://user-images.githubusercontent.com/830386/43939857-2b1ee87a-9c9f-11e8-8730-2b74669608ba.png)
Issue still persists using v.2.3.1

**Comment by Anima-t3d** [comment]
The solution posted in https://github.com/ibufu/vue2-scrollspy/issues/27#issuecomment-440257925 might solve this as well.

**Comment by ibufu** [comment]
@Anima-t3d thanks
