### ISSUE TITLE
Is there any chance to use this with Nuxt?

### ISSUE THREAD

**Issue by Addflow** [ibufu/vue2-scrollspy#34]
### Describe what you want:
It's working like a charm in Vue, but running the same code in Nuxt results in "ReferenceError: window is not defined".

Is there any workaround?

Thank you"

**Comment by Addflow** [comment]
Nevermind, it's working out of the box. If anyone else has trouble configuring it to run with Nuxt, here is the solution:

- if not exists, create a 'plugins' directory in project folder
- create file 'vue2-scrollspy.js'
- add code:
`import Vue from 'vue'
import Scrollspy, { Easing } from 'vue2-scrollspy'
Vue.use(Scrollspy, {
	easing: Easing.Cubic.InOut
})`
- extend your 'nuxt.config.js' file:
`module.exports = {
    plugins: [{ src: '~/plugins/vue2-scrollspy', ssr: false }]
}`

that's it :)

**Comment by BroTrue** [comment]
Anyway using this module is sh...
