### ISSUE TITLE
the initial value of data: section is not 1. is it? or how can I modify the initial value for section?

### ISSUE THREAD

**Issue by JustPlayN** [ibufu/vue2-scrollspy#35]
### vue2-scrollspy version: 2.3.1
```html
<div v-show="section > 0" v-scroll-spy-active="{class: 'banner-active'}" v-scroll-spy-link></div>
```
this div block in wxchat will show first. and then hide right now

**Comment by ibufu** [comment]
具体讲一下你想实现的效果

**Comment by JustPlayN** [comment]
我用v-scroll-spy="{data: 'section', offset: 50}"提供的section来控制导航的显示与隐藏，但是在微信里会默认先显示，然后再立即隐藏，我想直接隐藏，手动改变section时在显示

**Comment by ibufu** [comment]
可以 watch section，变化了之后把 v-show 变为 true
