### ISSUE TITLE
ERROR in static/js/vendor.5ee7f22f75ffddb52570.js from UglifyJs Invalid assignment ...

### ISSUE THREAD

**Issue by krrskl** [ibufu/vue2-scrollspy#37]
### Greetings, I am trying to run the command `npm run build`  and it is throwing me the following error:

`ERROR in static/js/vendor.5ee7f22f75ffddb52570.js from UglifyJs
Invalid assignment [./node_modules/vue2-scrollspy/src/index.js:3,0][static/js/vendor.5ee7f22f75ffddb52570.js:15901,31]`

**Comment by hesselberg** [comment]
@krrskl did you ever find a fix?

**Comment by ibufu** [comment]
@krrskl @hesselberg try use terser-webpack-plugin.
