### ISSUE TITLE
Accepting options (time, steps, offset...)

### ISSUE THREAD

**Issue by grzhan** [ibufu/vue2-scrollspy#6]
In [vue-scrollspy](https://github.com/kvdmolen/vue-scrollspy) , we can set animation options like this:
```html
<div v-scrollspy="scrollPos" :steps="30" :time="200" :offset="10">
```
However in [vue2-scrollspy](https://github.com/ibufu/vue2-scrollspy/blob/master/src/index.js#L54) , these parameters are constants, we can't tune them by ourselves. 

I hope `vue2-scrollspy` would accept such options.

In addition, maybe we should use a component rather than a directive to implement "scroll-spy", see https://github.com/vuejs/vue/issues/862:
> Directives in Vue2  are supposed to only handle simple mapping of a data property to some DOM manipulation.  If you want to have something that encapsulates more complex behavior, especially accepting options, you should just use a component instead.

I would appreciate it if you could give me an early reply.

**Comment by ibufu** [comment]
There will be a breaking change if turn it to a component. And it need more time to redesign. I will consider it later.

**Comment by exnihilo-creatio** [comment]
@ibufu The component can come later. It would be nice to have the options available sooner.
